// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/theme/Dark.tsx": () => import("../components/mockups/theme/Dark.tsx"),
  "./components/mockups/theme/Light.tsx": () => import("../components/mockups/theme/Light.tsx")
};
